In [2]:
import numpy
print(numpy.__version__)


2.1.3


In [5]:
import numpy as np

In [6]:
arr1=np.array([1,2,3])
print("1D array:",arr1)

1D array: [1 2 3]


In [10]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print("2D array:\n",arr2)

2D array:
 [[1 2 3]
 [4 5 6]]


In [12]:
arr3 =np.array([
    [[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]
               ])
print("3D array:\n" , arr3)

3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
print("shape array 1:", arr1.shape) #shape of 1D array

shape array 1: (3,)


In [18]:
print("shape array 2:",arr2.shape) #shape of 2D array

shape array 2: (2, 3)


In [19]:
print("shape array 3:",arr3.shape) #shape fo 3D array

shape array 3: (2, 2, 3)
