In [1]:
#basic statics

In [4]:
import numpy as np

In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print("Mean",np.mean(arr))
print("Mean along column:",np.mean(arr,axis=0))
print("Mean along rows:",np.mean(arr,axis=1))

Mean 5.0
Mean along column: [4. 5. 6.]
Mean along rows: [2. 5. 8.]


In [11]:
print("Median",np.median(arr))
print("Median along column:",np.median(arr,axis=0))
print("Median along rows:",np.median(arr,axis=1))

Median 5.0
Median along column: [4. 5. 6.]
Median along rows: [2. 5. 8.]


In [12]:
print("Standard Deviation:",np.std(arr))
print("along column:",np.std(arr,axis=0))
print("along rows:",np.std(arr,axis=1))

Standard Deviation: 2.581988897471611
along column: [2.44948974 2.44948974 2.44948974]
along rows: [0.81649658 0.81649658 0.81649658]


In [13]:
print("Minimum",np.min(arr))
print("Minimum along column:",np.min(arr,axis=0))
print("Minimum along rows:",np.min(arr,axis=1))

Minimum 1
Minimum along column: [1 2 3]
Minimum along rows: [1 4 7]


In [14]:
print("Maximum",np.max(arr))
print("Maximum along column:",np.max(arr,axis=0))
print("Maximum along rows:",np.max(arr,axis=1))

Maximum 9
Maximum along column: [7 8 9]
Maximum along rows: [3 6 9]
