In [1]:
#array manipulation

In [4]:
import numpy as np

In [15]:
arr = np.arange(1,13) 
print("Array:",arr)# arranged array

array= arr.reshape(3,4)
print("reshaped:\n",array) #reshaped

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
flat=array.flatten()
print("flatten array:\n",flat) #flatten

flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
a=np.array([[1,2],[4,5]])
b=np.array([[6,7],[9,10]])
print('concatenation along rows:\n',np.concatenate ((a,b), axis=0)) #contatenation along rows

concatenation along rows:
 [[ 1  2]
 [ 4  5]
 [ 6  7]
 [ 9 10]]


In [23]:
print('concatenation along columns:\n',np.concatenate ((a,b), axis=1)) #contatenation along columns

concatenation along columns:
 [[ 1  2  6  7]
 [ 4  5  9 10]]


In [46]:
a= np.arange(1,13)
b= a.reshape(4,3)
print("Reshaped:\n",b) #reshape array
print("Split the reshaped array into 3:",np.split(b,2,axis=0))

Reshaped:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Split the reshaped array into 3: [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
