In [1]:
#slicing of 1D arrays

In [6]:
import numpy as np

In [7]:
arr1 = np.array([1,2,3,4,5,6,7,8])
print(arr1[0:3]) # elements from index 0 to 2

[1 2 3]


In [8]:
arr1 = np.array([1,2,3,4,5,6,7,8])
print(arr1[3:]) # elements after 3

[4 5 6 7 8]


In [11]:
arr1 = np.array([1,2,3,4,5,6,7,8])
print(arr1[:5]) #first 5 elements

[1 2 3 4 5]


In [12]:
#slicing of 2D arrays

In [39]:
arr2 = np.array([[11,22,33,44,55],
                [66,77,88,99,100]])
print(arr2[0:1,0:3]) 

[[11 22 33]]


In [45]:
arr3=np.array([
  [[13,22,43],[20,51,66]], #layer 0
  [[56,72,38],[79,80,54]]  #layer 1
              ])

print(arr3[0,:,:]) #first layer

[[13 22 43]
 [20 51 66]]


In [46]:
print(arr3[:,0,:]) #first rows only

[[13 22 43]
 [56 72 38]]
