In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print("Addition:\n",a+b)

Addition:
 [ 7  9 11 13 15]


In [5]:
print("subtraction:\n",b-a)

subtraction:
 [5 5 5 5 5]


In [7]:
print("Multiplication:\n",b*a)

Multiplication:
 [ 6 14 24 36 50]


In [8]:
print("Division:\n",a/b)

Division:
 [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [14]:
array=np.array([1,4,9,25,36])

In [15]:
print("square root:\n",np.sqrt(array))

square root:
 [1. 2. 3. 5. 6.]


In [16]:
print("exponentional:\n",np.exp(array))

exponentional:
 [2.71828183e+00 5.45981500e+01 8.10308393e+03 7.20048993e+10
 4.31123155e+15]


In [17]:
print("sum:\n",np.sum(array))

sum:
 75


In [18]:
print("logarithm:\n",np.log(array))

logarithm:
 [0.         1.38629436 2.19722458 3.21887582 3.58351894]


In [19]:
print("mean:\n",np.mean(array))

mean:
 15.0


In [29]:
array=np.array([1,4,9,25,36])

In [30]:
print("a+5:\n",array+5)

a+5:
 [ 6  9 14 30 41]


In [31]:
b=np.array([[1],[2],[3]])
print("Broadcasting:\n",b+array)

Broadcasting:
 [[ 2  5 10 26 37]
 [ 3  6 11 27 38]
 [ 4  7 12 28 39]]


In [32]:
#NUMPY VS LIST

In [35]:
import time

In [37]:
size=1_000_000
# python list
list1=list(range(size))
list2=list(range(size))

start=time.time()
result=[list1[i] + list2[i] for i in range(size)]
end=time.time()
print("")
#Numpy array
arr1=np.arange(size)
arr2=np.arange(size)
